# Generated by Django 4.0.8 on 2023-01-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachers_name', models.TextField(max_length=20)),
                ('country', models.TextField(blank=True, default='Ukraine', max_length=20, null=True)),
                ('city', models.TextField(blank=True, max_length=30, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('facebook_link', models.CharField(blank=True, max_length=100, null=True)),
                ('telegram_link', models.CharField(blank=True, max_length=50, null=True)),
                ('instagram_link', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.CharField(max_length=250)),
                ('info', models.TextField()),
                ('speciality', models.CharField(max_length=250)),
            ],
        ),
    ]
