# Generated by Django 4.0.8 on 2023-01-05 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_instrument', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_instrument', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.category')),
            ],
            options={
                'verbose_name_plural': 'instruments',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('facebook_link', models.CharField(max_length=100, null=True)),
                ('telegram_link', models.CharField(max_length=50, null=True)),
                ('instagram_link', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('country', models.CharField(default='Ukraine', max_length=30, null=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('message', models.TextField()),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.instrument')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.seller')),
            ],
            options={
                'verbose_name_plural': 'products',
            },
        ),
    ]
